version: '3.3'

services:
  jenkins: 
    build: 
      context: .
      args:
        JAVA_OPTS: '-Djenkins.CLI.disabled=true'
    ports: 
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins_home_summit:/var/jenkins_home
      - ./casc_configs:/var/jenkins_conf
    secrets:
      - github  #Github username with password as an example. Purpose here is to have a user with write-access for special cases. Like the git-publisher.
      - adminpw  #Initial adminstrator user password. Added for debugging purposes. Should be removed prior to go-live.
    #  - Pass: ${{ secrets.PASSWORD }}
    #  - User: ${{ secrets.USERNAME }}
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_conf
secrets: 
  adminpw:
     file: secret/adminpw.txt

volumes:
  jenkins_home_summit:
